name = input("Enter your name:")
age = input("Enter your age:")
height = input("Enter your heighr(in cm):")
gender = input("Enter your gender:")
print("\n---Student Detail ---")
print("Name:", name)
print("Age:",age)
print("Height:", height, "cm")
print("Gender:",gender)